server:
  port: 8084

spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: rodrilang
    password: supersecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: notification-service-group
      auto-offset-reset: earliest
      properties:
        specific.avro.reader: true
    properties:
      schema.registry.url: http://localhost:8085
    listener:
      observation-enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"